CREATE SCHEMA BILLINGAPPDB;

CREATE TABLE ITEMINFO
(
FITEMID	INT UNSIGNED NOT NULL AUTO_INCREMENT
,FITEMNAME VARCHAR(50) NOT NULL
,FITEMDESC VARCHAR(200)
,FPRICE NUMERIC(6,2) NOT NULL
,FSTATUS CHAR(1) DEFAULT 'A'
,FCREATEDBY INT UNSIGNED
,FCREATEDDATE NUMERIC(8)
,FCREATEDTIME NUMERIC(6)
,FUPDATEDBY INT UNSIGNED
,FUPDATEDDATE NUMERIC(8)
,FUPDATEDTIME NUMERIC(6)
,FTIMESTAMP	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,CONSTRAINT PK_ITEM_ID PRIMARY KEY (FITEMID)
);

CREATE TABLE BILLINGINFO
(
FBILLINGID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT
,FCOMMENT VARCHAR(500)
,FTOTALPRICE NUMERIC(10,2) NOT NULL
,FSTATUS CHAR(1) DEFAULT 'A'
,FCREATEDBY INT UNSIGNED
,FCREATEDDATE NUMERIC(8)
,FCREATEDTIME NUMERIC(6)
,FUPDATEDBY INT UNSIGNED
,FUPDATEDDATE NUMERIC(8)
,FUPDATEDTIME NUMERIC(6)
,FTIMESTAMP	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,CONSTRAINT PK_BILLING_ID PRIMARY KEY (FBILLINGID)
);

CREATE TABLE BILLING_ITEMINFO
(
FBILLINGID BIGINT UNSIGNED NOT NULL
,FITEMID INT UNSIGNED
,FITEMPRICE NUMERIC(6,2)
,FQTY NUMERIC(3)
,CONSTRAINT FK_BILLING_ID FOREIGN KEY (FBILLINGID) REFERENCES BILLINGINFO(FBILLINGID)
);

CREATE TABLE USERINFO
(
FUSERID INT UNSIGNED NOT NULL AUTO_INCREMENT
,FUSERNAME VARCHAR(50) NOT NULL
,FPASSWORD VARCHAR(100) NOT NULL
,FFIRSTNAME VARCHAR(50) NOT NULL
,FLASTNAME VARCHAR(50)
,FSTATUS CHAR(1) DEFAULT 'A'
,FACCESSLEVEL NUMERIC(2) DEFAULT 2
,FCREATEDBY INT UNSIGNED
,FCREATEDDATE NUMERIC(8)
,FCREATEDTIME NUMERIC(6)
,FUPDATEDBY INT UNSIGNED
,FUPDATEDDATE NUMERIC(8)
,FUPDATEDTIME NUMERIC(6)
,FTIMESTAMP	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,CONSTRAINT PK_USER_ID PRIMARY KEY (FUSERID)
);

INSERT INTO USERINFO (FUSERNAME,FPASSWORD,FFIRSTNAME,FLASTNAME,FACCESSLEVEL)
VALUES('ADMIN','pass123','ADMIN','ADMIN',1);